const ERROR_CODES = {
  USER: {
    NOT_FOUND: "USER_NOT_FOUND",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    INVALID_EMAIL: "INVALID_EMAIL",
  },
};
