const ERROR_CODES = {
  SERVER: {
    INTERNAL_SERVER_ERROR: 1000,
    EMAIL_SEND_ERROR: 1001,
  },
  USER: {
    NOT_FOUND: 2000,
    INVALID_CREDENTIALS: 2001,
    EMAIL_ALREADY_EXISTS: 2002,
    INVALID_EMAIL: 2003,
  },
};

module.exports = ERROR_CODES;
